### ISSUE TITLE
Make extension Per Machine to have it show up in Experimental Instance

### ISSUE THREAD

**Issue by madskristensen** [pharring/SettingsStoreExplorer#51]

**Comment by pharring** [comment]
The downside of "Per Machine" extensions is that they don't get auto-updated; they require user-intervention and elevation to update.

If users want to install it in the Experimental instance, then can't they just do exactly that? Launch the Experimental Instance and install it via the Extensions UI?

**Comment by madskristensen** [comment]
Per-machine extensions do get automatic updates. However, it requires VS to be shut down and is then triggered at night. So it could potentially be weeks before an auto-update occur after the release of a new version

**Comment by pharring** [comment]
Thanks for the request, Mads and the PR. I've decided to stay with _Per User_.
