### ISSUE TITLE
Add roaming settings?

### ISSUE THREAD

**Issue by AArnott** [pharring/SettingsStoreExplorer#53]
Now that we have remote, config and user settings, how about rounding it out with a tree for *roaming* settings?

**Comment by pharring** [comment]
Is that a thing? Is it just another scope? (https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.__vsenclosingscopes)

**Comment by pharring** [comment]
I'm researching this, but if you have any pointers please drop them here.

**Comment by AArnott** [comment]
Yes. I think there's a VSIX that shows roaming settings already (or at least lets you clear them). @JoshuaBStevens would know for sure.

But even if there's already an extension, consolidating the two extensions might be good.
