### ISSUE TITLE
Enable Copy command for values under Config hive

### ISSUE THREAD

**Issue by AArnott** [pharring/SettingsStoreExplorer#58]
Short of #37, I can't even copy registry values from the read only config hive. I see package GUIDs and then I want to search for them elsewhere. But I can't right click or use Ctrl+C to activate a Copy command on config values.

It would be nice to Copy key names as well, anywhere in the tree.

**Comment by pharring** [comment]
Good suggestion.

**Comment by pharring** [comment]
Add:
- "Copy Key Name" on the keys context menu
- "Copy Name" on properties context menu
- "Copy Value" on properties context menu
